// @generated by protobuf-ts 2.9.4
// @generated from protobuf file "Greeter.proto" (package "Greeter", syntax proto3)
// tslint:disable
import { ServiceType } from "@protobuf-ts/runtime-rpc";
import type { BinaryWriteOptions } from "@protobuf-ts/runtime";
import type { IBinaryWriter } from "@protobuf-ts/runtime";
import { WireType } from "@protobuf-ts/runtime";
import type { BinaryReadOptions } from "@protobuf-ts/runtime";
import type { IBinaryReader } from "@protobuf-ts/runtime";
import { UnknownFieldHandler } from "@protobuf-ts/runtime";
import type { PartialMessage } from "@protobuf-ts/runtime";
import { reflectionMergePartial } from "@protobuf-ts/runtime";
import { MessageType } from "@protobuf-ts/runtime";
/**
 * The request message containing requested numbers
 *
 * @generated from protobuf message Greeter.GreetRequest
 */
export interface GreetRequest {
    /**
     * @generated from protobuf field: string name = 1;
     */
    name: string;
}
/**
 * The response message containing response
 *
 * @generated from protobuf message Greeter.GreetReply
 */
export interface GreetReply {
    /**
     * @generated from protobuf field: string res = 1;
     */
    res: string;
}
// @generated message type with reflection information, may provide speed optimized methods
class GreetRequest$Type extends MessageType<GreetRequest> {
    constructor() {
        super("Greeter.GreetRequest", [
            { no: 1, name: "name", kind: "scalar", T: 9 /*ScalarType.STRING*/ }
        ]);
    }
    create(value?: PartialMessage<GreetRequest>): GreetRequest {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.name = "";
        if (value !== undefined)
            reflectionMergePartial<GreetRequest>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: GreetRequest): GreetRequest {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* string name */ 1:
                    message.name = reader.string();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: GreetRequest, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* string name = 1; */
        if (message.name !== "")
            writer.tag(1, WireType.LengthDelimited).string(message.name);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message Greeter.GreetRequest
 */
export const GreetRequest = new GreetRequest$Type();
// @generated message type with reflection information, may provide speed optimized methods
class GreetReply$Type extends MessageType<GreetReply> {
    constructor() {
        super("Greeter.GreetReply", [
            { no: 1, name: "res", kind: "scalar", T: 9 /*ScalarType.STRING*/ }
        ]);
    }
    create(value?: PartialMessage<GreetReply>): GreetReply {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.res = "";
        if (value !== undefined)
            reflectionMergePartial<GreetReply>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: GreetReply): GreetReply {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* string res */ 1:
                    message.res = reader.string();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: GreetReply, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* string res = 1; */
        if (message.res !== "")
            writer.tag(1, WireType.LengthDelimited).string(message.res);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message Greeter.GreetReply
 */
export const GreetReply = new GreetReply$Type();
/**
 * @generated ServiceType for protobuf service Greeter.Greeter
 */
export const Greeter = new ServiceType("Greeter.Greeter", [
    { name: "GetGreeting", options: {}, I: GreetRequest, O: GreetReply }
]);
