// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: Greeter.proto
#ifndef GRPC_Greeter_2eproto__INCLUDED
#define GRPC_Greeter_2eproto__INCLUDED

#include "Greeter.pb.h"

#include <functional>
#include <grpcpp/generic/async_generic_service.h>
#include <grpcpp/support/async_stream.h>
#include <grpcpp/support/async_unary_call.h>
#include <grpcpp/support/client_callback.h>
#include <grpcpp/client_context.h>
#include <grpcpp/completion_queue.h>
#include <grpcpp/support/message_allocator.h>
#include <grpcpp/support/method_handler.h>
#include <grpcpp/impl/proto_utils.h>
#include <grpcpp/impl/rpc_method.h>
#include <grpcpp/support/server_callback.h>
#include <grpcpp/impl/server_callback_handlers.h>
#include <grpcpp/server_context.h>
#include <grpcpp/impl/service_type.h>
#include <grpcpp/support/status.h>
#include <grpcpp/support/stub_options.h>
#include <grpcpp/support/sync_stream.h>

namespace Greeter {

// Defines the service
class Greeter final {
 public:
  static constexpr char const* service_full_name() {
    return "Greeter.Greeter";
  }
  class StubInterface {
   public:
    virtual ~StubInterface() {}
    // Function invoked to send the request
    virtual ::grpc::Status GetGreeting(::grpc::ClientContext* context, const ::Greeter::GreetRequest& request, ::Greeter::GreetReply* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::Greeter::GreetReply>> AsyncGetGreeting(::grpc::ClientContext* context, const ::Greeter::GreetRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::Greeter::GreetReply>>(AsyncGetGreetingRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::Greeter::GreetReply>> PrepareAsyncGetGreeting(::grpc::ClientContext* context, const ::Greeter::GreetRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::Greeter::GreetReply>>(PrepareAsyncGetGreetingRaw(context, request, cq));
    }
    class async_interface {
     public:
      virtual ~async_interface() {}
      // Function invoked to send the request
      virtual void GetGreeting(::grpc::ClientContext* context, const ::Greeter::GreetRequest* request, ::Greeter::GreetReply* response, std::function<void(::grpc::Status)>) = 0;
      virtual void GetGreeting(::grpc::ClientContext* context, const ::Greeter::GreetRequest* request, ::Greeter::GreetReply* response, ::grpc::ClientUnaryReactor* reactor) = 0;
    };
    typedef class async_interface experimental_async_interface;
    virtual class async_interface* async() { return nullptr; }
    class async_interface* experimental_async() { return async(); }
   private:
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::Greeter::GreetReply>* AsyncGetGreetingRaw(::grpc::ClientContext* context, const ::Greeter::GreetRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::Greeter::GreetReply>* PrepareAsyncGetGreetingRaw(::grpc::ClientContext* context, const ::Greeter::GreetRequest& request, ::grpc::CompletionQueue* cq) = 0;
  };
  class Stub final : public StubInterface {
   public:
    Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());
    ::grpc::Status GetGreeting(::grpc::ClientContext* context, const ::Greeter::GreetRequest& request, ::Greeter::GreetReply* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::Greeter::GreetReply>> AsyncGetGreeting(::grpc::ClientContext* context, const ::Greeter::GreetRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::Greeter::GreetReply>>(AsyncGetGreetingRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::Greeter::GreetReply>> PrepareAsyncGetGreeting(::grpc::ClientContext* context, const ::Greeter::GreetRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::Greeter::GreetReply>>(PrepareAsyncGetGreetingRaw(context, request, cq));
    }
    class async final :
      public StubInterface::async_interface {
     public:
      void GetGreeting(::grpc::ClientContext* context, const ::Greeter::GreetRequest* request, ::Greeter::GreetReply* response, std::function<void(::grpc::Status)>) override;
      void GetGreeting(::grpc::ClientContext* context, const ::Greeter::GreetRequest* request, ::Greeter::GreetReply* response, ::grpc::ClientUnaryReactor* reactor) override;
     private:
      friend class Stub;
      explicit async(Stub* stub): stub_(stub) { }
      Stub* stub() { return stub_; }
      Stub* stub_;
    };
    class async* async() override { return &async_stub_; }

   private:
    std::shared_ptr< ::grpc::ChannelInterface> channel_;
    class async async_stub_{this};
    ::grpc::ClientAsyncResponseReader< ::Greeter::GreetReply>* AsyncGetGreetingRaw(::grpc::ClientContext* context, const ::Greeter::GreetRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::Greeter::GreetReply>* PrepareAsyncGetGreetingRaw(::grpc::ClientContext* context, const ::Greeter::GreetRequest& request, ::grpc::CompletionQueue* cq) override;
    const ::grpc::internal::RpcMethod rpcmethod_GetGreeting_;
  };
  static std::unique_ptr<Stub> NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());

  class Service : public ::grpc::Service {
   public:
    Service();
    virtual ~Service();
    // Function invoked to send the request
    virtual ::grpc::Status GetGreeting(::grpc::ServerContext* context, const ::Greeter::GreetRequest* request, ::Greeter::GreetReply* response);
  };
  template <class BaseClass>
  class WithAsyncMethod_GetGreeting : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_GetGreeting() {
      ::grpc::Service::MarkMethodAsync(0);
    }
    ~WithAsyncMethod_GetGreeting() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetGreeting(::grpc::ServerContext* /*context*/, const ::Greeter::GreetRequest* /*request*/, ::Greeter::GreetReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestGetGreeting(::grpc::ServerContext* context, ::Greeter::GreetRequest* request, ::grpc::ServerAsyncResponseWriter< ::Greeter::GreetReply>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  typedef WithAsyncMethod_GetGreeting<Service > AsyncService;
  template <class BaseClass>
  class WithCallbackMethod_GetGreeting : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_GetGreeting() {
      ::grpc::Service::MarkMethodCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::Greeter::GreetRequest, ::Greeter::GreetReply>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::Greeter::GreetRequest* request, ::Greeter::GreetReply* response) { return this->GetGreeting(context, request, response); }));}
    void SetMessageAllocatorFor_GetGreeting(
        ::grpc::MessageAllocator< ::Greeter::GreetRequest, ::Greeter::GreetReply>* allocator) {
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(0);
      static_cast<::grpc::internal::CallbackUnaryHandler< ::Greeter::GreetRequest, ::Greeter::GreetReply>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~WithCallbackMethod_GetGreeting() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetGreeting(::grpc::ServerContext* /*context*/, const ::Greeter::GreetRequest* /*request*/, ::Greeter::GreetReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* GetGreeting(
      ::grpc::CallbackServerContext* /*context*/, const ::Greeter::GreetRequest* /*request*/, ::Greeter::GreetReply* /*response*/)  { return nullptr; }
  };
  typedef WithCallbackMethod_GetGreeting<Service > CallbackService;
  typedef CallbackService ExperimentalCallbackService;
  template <class BaseClass>
  class WithGenericMethod_GetGreeting : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_GetGreeting() {
      ::grpc::Service::MarkMethodGeneric(0);
    }
    ~WithGenericMethod_GetGreeting() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetGreeting(::grpc::ServerContext* /*context*/, const ::Greeter::GreetRequest* /*request*/, ::Greeter::GreetReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithRawMethod_GetGreeting : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_GetGreeting() {
      ::grpc::Service::MarkMethodRaw(0);
    }
    ~WithRawMethod_GetGreeting() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetGreeting(::grpc::ServerContext* /*context*/, const ::Greeter::GreetRequest* /*request*/, ::Greeter::GreetReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestGetGreeting(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_GetGreeting : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_GetGreeting() {
      ::grpc::Service::MarkMethodRawCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->GetGreeting(context, request, response); }));
    }
    ~WithRawCallbackMethod_GetGreeting() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetGreeting(::grpc::ServerContext* /*context*/, const ::Greeter::GreetRequest* /*request*/, ::Greeter::GreetReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* GetGreeting(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_GetGreeting : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_GetGreeting() {
      ::grpc::Service::MarkMethodStreamed(0,
        new ::grpc::internal::StreamedUnaryHandler<
          ::Greeter::GreetRequest, ::Greeter::GreetReply>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::Greeter::GreetRequest, ::Greeter::GreetReply>* streamer) {
                       return this->StreamedGetGreeting(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_GetGreeting() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status GetGreeting(::grpc::ServerContext* /*context*/, const ::Greeter::GreetRequest* /*request*/, ::Greeter::GreetReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedGetGreeting(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::Greeter::GreetRequest,::Greeter::GreetReply>* server_unary_streamer) = 0;
  };
  typedef WithStreamedUnaryMethod_GetGreeting<Service > StreamedUnaryService;
  typedef Service SplitStreamedService;
  typedef WithStreamedUnaryMethod_GetGreeting<Service > StreamedService;
};

}  // namespace Greeter


#endif  // GRPC_Greeter_2eproto__INCLUDED
