// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: Greeter.proto

#include "Greeter.pb.h"
#include "Greeter.grpc.pb.h"

#include <functional>
#include <grpcpp/support/async_stream.h>
#include <grpcpp/support/async_unary_call.h>
#include <grpcpp/impl/channel_interface.h>
#include <grpcpp/impl/client_unary_call.h>
#include <grpcpp/support/client_callback.h>
#include <grpcpp/support/message_allocator.h>
#include <grpcpp/support/method_handler.h>
#include <grpcpp/impl/rpc_service_method.h>
#include <grpcpp/support/server_callback.h>
#include <grpcpp/impl/server_callback_handlers.h>
#include <grpcpp/server_context.h>
#include <grpcpp/impl/service_type.h>
#include <grpcpp/support/sync_stream.h>
namespace Greeter {

static const char* Greeter_method_names[] = {
  "/Greeter.Greeter/GetGreeting",
};

std::unique_ptr< Greeter::Stub> Greeter::NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options) {
  (void)options;
  std::unique_ptr< Greeter::Stub> stub(new Greeter::Stub(channel, options));
  return stub;
}

Greeter::Stub::Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options)
  : channel_(channel), rpcmethod_GetGreeting_(Greeter_method_names[0], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  {}

::grpc::Status Greeter::Stub::GetGreeting(::grpc::ClientContext* context, const ::Greeter::GreetRequest& request, ::Greeter::GreetReply* response) {
  return ::grpc::internal::BlockingUnaryCall< ::Greeter::GreetRequest, ::Greeter::GreetReply, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_GetGreeting_, context, request, response);
}

void Greeter::Stub::async::GetGreeting(::grpc::ClientContext* context, const ::Greeter::GreetRequest* request, ::Greeter::GreetReply* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::Greeter::GreetRequest, ::Greeter::GreetReply, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_GetGreeting_, context, request, response, std::move(f));
}

void Greeter::Stub::async::GetGreeting(::grpc::ClientContext* context, const ::Greeter::GreetRequest* request, ::Greeter::GreetReply* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_GetGreeting_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::Greeter::GreetReply>* Greeter::Stub::PrepareAsyncGetGreetingRaw(::grpc::ClientContext* context, const ::Greeter::GreetRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::Greeter::GreetReply, ::Greeter::GreetRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_GetGreeting_, context, request);
}

::grpc::ClientAsyncResponseReader< ::Greeter::GreetReply>* Greeter::Stub::AsyncGetGreetingRaw(::grpc::ClientContext* context, const ::Greeter::GreetRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncGetGreetingRaw(context, request, cq);
  result->StartCall();
  return result;
}

Greeter::Service::Service() {
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      Greeter_method_names[0],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< Greeter::Service, ::Greeter::GreetRequest, ::Greeter::GreetReply, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](Greeter::Service* service,
             ::grpc::ServerContext* ctx,
             const ::Greeter::GreetRequest* req,
             ::Greeter::GreetReply* resp) {
               return service->GetGreeting(ctx, req, resp);
             }, this)));
}

Greeter::Service::~Service() {
}

::grpc::Status Greeter::Service::GetGreeting(::grpc::ServerContext* context, const ::Greeter::GreetRequest* request, ::Greeter::GreetReply* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}


}  // namespace Greeter

