// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Greeter.proto

#include "Greeter.pb.h"

#include <algorithm>
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/extension_set.h"
#include "google/protobuf/wire_format_lite.h"
#include "google/protobuf/descriptor.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/reflection_ops.h"
#include "google/protobuf/wire_format.h"
#include "google/protobuf/generated_message_tctable_impl.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"
PROTOBUF_PRAGMA_INIT_SEG
namespace _pb = ::google::protobuf;
namespace _pbi = ::google::protobuf::internal;
namespace _fl = ::google::protobuf::internal::field_layout;
namespace Greeter {

inline constexpr GreetRequest::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : name_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        _cached_size_{0} {}

template <typename>
PROTOBUF_CONSTEXPR GreetRequest::GreetRequest(::_pbi::ConstantInitialized)
    : _impl_(::_pbi::ConstantInitialized()) {}
struct GreetRequestDefaultTypeInternal {
  PROTOBUF_CONSTEXPR GreetRequestDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~GreetRequestDefaultTypeInternal() {}
  union {
    GreetRequest _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 GreetRequestDefaultTypeInternal _GreetRequest_default_instance_;

inline constexpr GreetReply::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : res_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        _cached_size_{0} {}

template <typename>
PROTOBUF_CONSTEXPR GreetReply::GreetReply(::_pbi::ConstantInitialized)
    : _impl_(::_pbi::ConstantInitialized()) {}
struct GreetReplyDefaultTypeInternal {
  PROTOBUF_CONSTEXPR GreetReplyDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~GreetReplyDefaultTypeInternal() {}
  union {
    GreetReply _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 GreetReplyDefaultTypeInternal _GreetReply_default_instance_;
}  // namespace Greeter
static ::_pb::Metadata file_level_metadata_Greeter_2eproto[2];
static constexpr const ::_pb::EnumDescriptor**
    file_level_enum_descriptors_Greeter_2eproto = nullptr;
static constexpr const ::_pb::ServiceDescriptor**
    file_level_service_descriptors_Greeter_2eproto = nullptr;
const ::uint32_t TableStruct_Greeter_2eproto::offsets[] PROTOBUF_SECTION_VARIABLE(
    protodesc_cold) = {
    ~0u,  // no _has_bits_
    PROTOBUF_FIELD_OFFSET(::Greeter::GreetRequest, _internal_metadata_),
    ~0u,  // no _extensions_
    ~0u,  // no _oneof_case_
    ~0u,  // no _weak_field_map_
    ~0u,  // no _inlined_string_donated_
    ~0u,  // no _split_
    ~0u,  // no sizeof(Split)
    PROTOBUF_FIELD_OFFSET(::Greeter::GreetRequest, _impl_.name_),
    ~0u,  // no _has_bits_
    PROTOBUF_FIELD_OFFSET(::Greeter::GreetReply, _internal_metadata_),
    ~0u,  // no _extensions_
    ~0u,  // no _oneof_case_
    ~0u,  // no _weak_field_map_
    ~0u,  // no _inlined_string_donated_
    ~0u,  // no _split_
    ~0u,  // no sizeof(Split)
    PROTOBUF_FIELD_OFFSET(::Greeter::GreetReply, _impl_.res_),
};

static const ::_pbi::MigrationSchema
    schemas[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
        {0, -1, -1, sizeof(::Greeter::GreetRequest)},
        {9, -1, -1, sizeof(::Greeter::GreetReply)},
};

static const ::_pb::Message* const file_default_instances[] = {
    &::Greeter::_GreetRequest_default_instance_._instance,
    &::Greeter::_GreetReply_default_instance_._instance,
};
const char descriptor_table_protodef_Greeter_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
    "\n\rGreeter.proto\022\007Greeter\"\034\n\014GreetRequest"
    "\022\014\n\004name\030\001 \001(\t\"\031\n\nGreetReply\022\013\n\003res\030\001 \001("
    "\t2F\n\007Greeter\022;\n\013GetGreeting\022\025.Greeter.Gr"
    "eetRequest\032\023.Greeter.GreetReply\"\000b\006proto"
    "3"
};
static ::absl::once_flag descriptor_table_Greeter_2eproto_once;
const ::_pbi::DescriptorTable descriptor_table_Greeter_2eproto = {
    false,
    false,
    161,
    descriptor_table_protodef_Greeter_2eproto,
    "Greeter.proto",
    &descriptor_table_Greeter_2eproto_once,
    nullptr,
    0,
    2,
    schemas,
    file_default_instances,
    TableStruct_Greeter_2eproto::offsets,
    file_level_metadata_Greeter_2eproto,
    file_level_enum_descriptors_Greeter_2eproto,
    file_level_service_descriptors_Greeter_2eproto,
};

// This function exists to be marked as weak.
// It can significantly speed up compilation by breaking up LLVM's SCC
// in the .pb.cc translation units. Large translation units see a
// reduction of more than 35% of walltime for optimized builds. Without
// the weak attribute all the messages in the file, including all the
// vtables and everything they use become part of the same SCC through
// a cycle like:
// GetMetadata -> descriptor table -> default instances ->
//   vtables -> GetMetadata
// By adding a weak function here we break the connection from the
// individual vtables back into the descriptor table.
PROTOBUF_ATTRIBUTE_WEAK const ::_pbi::DescriptorTable* descriptor_table_Greeter_2eproto_getter() {
  return &descriptor_table_Greeter_2eproto;
}
// Force running AddDescriptors() at dynamic initialization time.
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2
static ::_pbi::AddDescriptorsRunner dynamic_init_dummy_Greeter_2eproto(&descriptor_table_Greeter_2eproto);
namespace Greeter {
// ===================================================================

class GreetRequest::_Internal {
 public:
};

GreetRequest::GreetRequest(::google::protobuf::Arena* arena)
    : ::google::protobuf::Message(arena) {
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:Greeter.GreetRequest)
}
inline PROTOBUF_NDEBUG_INLINE GreetRequest::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility, ::google::protobuf::Arena* arena,
    const Impl_& from)
      : name_(arena, from.name_),
        _cached_size_{0} {}

GreetRequest::GreetRequest(
    ::google::protobuf::Arena* arena,
    const GreetRequest& from)
    : ::google::protobuf::Message(arena) {
  GreetRequest* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_);

  // @@protoc_insertion_point(copy_constructor:Greeter.GreetRequest)
}
inline PROTOBUF_NDEBUG_INLINE GreetRequest::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : name_(arena),
        _cached_size_{0} {}

inline void GreetRequest::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
}
GreetRequest::~GreetRequest() {
  // @@protoc_insertion_point(destructor:Greeter.GreetRequest)
  _internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  SharedDtor();
}
inline void GreetRequest::SharedDtor() {
  ABSL_DCHECK(GetArena() == nullptr);
  _impl_.name_.Destroy();
  _impl_.~Impl_();
}

PROTOBUF_NOINLINE void GreetRequest::Clear() {
// @@protoc_insertion_point(message_clear_start:Greeter.GreetRequest)
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.name_.ClearToEmpty();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

const char* GreetRequest::_InternalParse(
    const char* ptr, ::_pbi::ParseContext* ctx) {
  ptr = ::_pbi::TcParser::ParseLoop(this, ptr, ctx, &_table_.header);
  return ptr;
}


PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<0, 1, 0, 33, 2> GreetRequest::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    1, 0,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967294,  // skipmap
    offsetof(decltype(_table_), field_entries),
    1,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    &_GreetRequest_default_instance_._instance,
    ::_pbi::TcParser::GenericFallback,  // fallback
  }, {{
    // string name = 1;
    {::_pbi::TcParser::FastUS1,
     {10, 63, 0, PROTOBUF_FIELD_OFFSET(GreetRequest, _impl_.name_)}},
  }}, {{
    65535, 65535
  }}, {{
    // string name = 1;
    {PROTOBUF_FIELD_OFFSET(GreetRequest, _impl_.name_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUtf8String | ::_fl::kRepAString)},
  }},
  // no aux_entries
  {{
    "\24\4\0\0\0\0\0\0"
    "Greeter.GreetRequest"
    "name"
  }},
};

::uint8_t* GreetRequest::_InternalSerialize(
    ::uint8_t* target,
    ::google::protobuf::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:Greeter.GreetRequest)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  // string name = 1;
  if (!this->_internal_name().empty()) {
    const std::string& _s = this->_internal_name();
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
        _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "Greeter.GreetRequest.name");
    target = stream->WriteStringMaybeAliased(1, _s, target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:Greeter.GreetRequest)
  return target;
}

::size_t GreetRequest::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:Greeter.GreetRequest)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // string name = 1;
  if (!this->_internal_name().empty()) {
    total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                    this->_internal_name());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::google::protobuf::Message::ClassData GreetRequest::_class_data_ = {
    GreetRequest::MergeImpl,
    nullptr,  // OnDemandRegisterArenaDtor
};
const ::google::protobuf::Message::ClassData* GreetRequest::GetClassData() const {
  return &_class_data_;
}

void GreetRequest::MergeImpl(::google::protobuf::Message& to_msg, const ::google::protobuf::Message& from_msg) {
  auto* const _this = static_cast<GreetRequest*>(&to_msg);
  auto& from = static_cast<const GreetRequest&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:Greeter.GreetRequest)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (!from._internal_name().empty()) {
    _this->_internal_set_name(from._internal_name());
  }
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void GreetRequest::CopyFrom(const GreetRequest& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:Greeter.GreetRequest)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

PROTOBUF_NOINLINE bool GreetRequest::IsInitialized() const {
  return true;
}

::_pbi::CachedSize* GreetRequest::AccessCachedSize() const {
  return &_impl_._cached_size_;
}
void GreetRequest::InternalSwap(GreetRequest* PROTOBUF_RESTRICT other) {
  using std::swap;
  auto* arena = GetArena();
  ABSL_DCHECK_EQ(arena, other->GetArena());
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.name_, &other->_impl_.name_, arena);
}

::google::protobuf::Metadata GreetRequest::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_Greeter_2eproto_getter, &descriptor_table_Greeter_2eproto_once,
      file_level_metadata_Greeter_2eproto[0]);
}
// ===================================================================

class GreetReply::_Internal {
 public:
};

GreetReply::GreetReply(::google::protobuf::Arena* arena)
    : ::google::protobuf::Message(arena) {
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:Greeter.GreetReply)
}
inline PROTOBUF_NDEBUG_INLINE GreetReply::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility, ::google::protobuf::Arena* arena,
    const Impl_& from)
      : res_(arena, from.res_),
        _cached_size_{0} {}

GreetReply::GreetReply(
    ::google::protobuf::Arena* arena,
    const GreetReply& from)
    : ::google::protobuf::Message(arena) {
  GreetReply* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_);

  // @@protoc_insertion_point(copy_constructor:Greeter.GreetReply)
}
inline PROTOBUF_NDEBUG_INLINE GreetReply::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : res_(arena),
        _cached_size_{0} {}

inline void GreetReply::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
}
GreetReply::~GreetReply() {
  // @@protoc_insertion_point(destructor:Greeter.GreetReply)
  _internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  SharedDtor();
}
inline void GreetReply::SharedDtor() {
  ABSL_DCHECK(GetArena() == nullptr);
  _impl_.res_.Destroy();
  _impl_.~Impl_();
}

PROTOBUF_NOINLINE void GreetReply::Clear() {
// @@protoc_insertion_point(message_clear_start:Greeter.GreetReply)
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.res_.ClearToEmpty();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

const char* GreetReply::_InternalParse(
    const char* ptr, ::_pbi::ParseContext* ctx) {
  ptr = ::_pbi::TcParser::ParseLoop(this, ptr, ctx, &_table_.header);
  return ptr;
}


PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<0, 1, 0, 30, 2> GreetReply::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    1, 0,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967294,  // skipmap
    offsetof(decltype(_table_), field_entries),
    1,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    &_GreetReply_default_instance_._instance,
    ::_pbi::TcParser::GenericFallback,  // fallback
  }, {{
    // string res = 1;
    {::_pbi::TcParser::FastUS1,
     {10, 63, 0, PROTOBUF_FIELD_OFFSET(GreetReply, _impl_.res_)}},
  }}, {{
    65535, 65535
  }}, {{
    // string res = 1;
    {PROTOBUF_FIELD_OFFSET(GreetReply, _impl_.res_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUtf8String | ::_fl::kRepAString)},
  }},
  // no aux_entries
  {{
    "\22\3\0\0\0\0\0\0"
    "Greeter.GreetReply"
    "res"
  }},
};

::uint8_t* GreetReply::_InternalSerialize(
    ::uint8_t* target,
    ::google::protobuf::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:Greeter.GreetReply)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  // string res = 1;
  if (!this->_internal_res().empty()) {
    const std::string& _s = this->_internal_res();
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
        _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "Greeter.GreetReply.res");
    target = stream->WriteStringMaybeAliased(1, _s, target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:Greeter.GreetReply)
  return target;
}

::size_t GreetReply::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:Greeter.GreetReply)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // string res = 1;
  if (!this->_internal_res().empty()) {
    total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                    this->_internal_res());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::google::protobuf::Message::ClassData GreetReply::_class_data_ = {
    GreetReply::MergeImpl,
    nullptr,  // OnDemandRegisterArenaDtor
};
const ::google::protobuf::Message::ClassData* GreetReply::GetClassData() const {
  return &_class_data_;
}

void GreetReply::MergeImpl(::google::protobuf::Message& to_msg, const ::google::protobuf::Message& from_msg) {
  auto* const _this = static_cast<GreetReply*>(&to_msg);
  auto& from = static_cast<const GreetReply&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:Greeter.GreetReply)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (!from._internal_res().empty()) {
    _this->_internal_set_res(from._internal_res());
  }
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void GreetReply::CopyFrom(const GreetReply& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:Greeter.GreetReply)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

PROTOBUF_NOINLINE bool GreetReply::IsInitialized() const {
  return true;
}

::_pbi::CachedSize* GreetReply::AccessCachedSize() const {
  return &_impl_._cached_size_;
}
void GreetReply::InternalSwap(GreetReply* PROTOBUF_RESTRICT other) {
  using std::swap;
  auto* arena = GetArena();
  ABSL_DCHECK_EQ(arena, other->GetArena());
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.res_, &other->_impl_.res_, arena);
}

::google::protobuf::Metadata GreetReply::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_Greeter_2eproto_getter, &descriptor_table_Greeter_2eproto_once,
      file_level_metadata_Greeter_2eproto[1]);
}
// @@protoc_insertion_point(namespace_scope)
}  // namespace Greeter
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google
// @@protoc_insertion_point(global_scope)
#include "google/protobuf/port_undef.inc"
